### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by lcortess** [mpociot/slackbot#12]
Is there an issue with composer package?

I am trying to do `composer require mpociot/slackbot` and I get an error:

```
 [InvalidArgumentException]                                                   
  Could not find package mpociot/slackbot at any version for your minimum-sta  
  bility (stable). Check the package spelling or your minimum-stability  
```

**Comment by mpociot** [comment]
I hadn't tagged a release yet - that's why composer was complaining. 
The release is now tagged and after clearing your composer cache, everything will work.
