### ISSUE TITLE
Attachment builder for message object

### ISSUE THREAD

**Issue by ramizmoh** [mpociot/slackbot#18]
Hi

The documentation makes reference to creating a message object when wanting to create 'pretty' messages.

> Slack-specific fields and attachments:

Is it possible for you to include a function to the slackbot class that allows for attachments to be added to the bot->reply, with an attachment builder | attachment object as a parameter?

Otherwise, a message object parameter that can build attachments too.

Regards

**Comment by jryd** [comment]
This would be great.

I've tried doing it likes this:

```
$bot->reply('Look a pretty image, [
                    'attachments' => [
                        'image_url' => 'imageurl',
                    ]
                ]);
```

and like this:

```
$bot->reply('Look a pretty image, [
    'image_url' => 'imageurl',
 ]);
```

Without any luck so far.

Have you been able to get it to work @ramizmoh?

**Comment by ramizmoh** [comment]
Hi James

I have not specifically implemented it yet; but I was intending on creating a new class by extending the Question object.

Currently, this object does the bulk of the heavy lifting, which includes interactive messages.

**Comment by mpociot** [comment]
@jryd I think the problem is, that the attachments need to be JSON encoded.

Try this instead:

```php
$bot->reply('Look a pretty image, [
    'attachments' =>json_encode( [
        'image_url' => 'imageurl',
    ])
]);
```

**Comment by jryd** [comment]
@mpociot that still doesn't work for me.

Is there anyway to debug where it is going wrong? I get the `Look a pretty image` come through but no image - despite the URL being valid.

**Comment by jryd** [comment]
@mpociot looking in to the `reply()` function a little more I see it looks like this:

```
/**
     * @param string|Question $message
     * @param array $additionalParameters
     * @return $this
     */
    public function reply($message, $additionalParameters = [])
    {
        $parameters = array_merge([
            'token' => $this->payload->get('token'),
            'channel' => $this->getChannel(),
            'text' => $message,
        ], $additionalParameters);
        /*
         * If we send a Question with buttons, ignore
         * the text and append the question.
         */
        if ($message instanceof Question) {
            $parameters['text'] = '';
            $parameters['attachments'] = json_encode([$message->toArray()]);
        }
        $this->commander->execute('chat.postMessage', $parameters);
        return $this;
    }
```

The `instanceOf Question` seems to allow it to send `attachments` which is where the `image_url` needs to be defined. Is there a way to extract that out in to a new function to use?

**Comment by mpociot** [comment]
Okay, I double checked this now.

According to the Slack `chat.postMessage` API (https://api.slack.com/methods/chat.postMessage) the `attachments` need to be a JSON encoded array, containing objects for each attachment.

So you can do this:

```php
$bot->reply('Look a pretty image, [
    'attachments' =>json_encode( [
        [
            'image_url' => 'imageurl',
        ]
    ])
]);
```

**Comment by jryd** [comment]
@mpociot have you tested that at all?

That's what you suggested before, but as I said it **doesn't work**.

The message:

> Look a pretty image

comes through, but no image - and when I try the URL inside the Slack API message builder it works fine so I know it isn't the URL.

Anything else you can suggest to get this going?

**Comment by mpociot** [comment]
@jryd - yes I **have** tested this and **no** - this is not what I suggested before.

```
$bot->reply('Hello', [
    'attachments' => json_encode([
        [
            'title' => 'Foo',
            'image_url' => 'https://brandfolder.com/slack/logo/slack-primary-logo.png'
        ]
    ])
]);
```
Which results in this:

<img width="493" alt="screen shot 2016-11-23 at 09 34 55" src="https://cloud.githubusercontent.com/assets/804684/20555059/1f528d98-b160-11e6-9b87-439369783524.png">

**Comment by jryd** [comment]
@mpociot I could've sworn that was what I was doing before, but it works just fine now! Thanks!

I just have one more question, I'm successfully using that when replying with the bot, but when inside a conversation this doesn't seem to work for me with:

```
$this->say('Hello', [
   'attachments' => json_encode([
        [
           'title' => 'Foo',
           'image_url' => 'https://brandfolder.com/slack/logo/slack-primary-logo.png'
        ]
    ])
]);
```

From what I can see inside the `Conversation` file, `$this->say` is going through `reply()` anyway right?

```
public function say($message)
{
    $this->bot->reply($message);
    return $this;
}
```

Much like with my troubles before 

> Hello

comes through fine but with no attachment. What am I doing wrong?

**Comment by mpociot** [comment]
The `say` method did not accept additional parameters. I fixed this in the latest commit https://github.com/mpociot/slackbot/commit/5084127139ca679a5eb59c79a928742536c2b30e and published a new release

**Comment by jryd** [comment]
Thanks for all your help!

**Comment by kurilov** [comment]
You need to add in the FAQ. I spent a lot of time before you found this answer. ;)

**Comment by mpociot** [comment]
Thanks for mentioning. Will do!
